DROP TABLE picture;


CREATE TABLE picture(
	id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	url VARCHAR(2083) NOT NULL,
	description VARCHAR(255) NOT NULL
	)ENGINE=InnoDB DEFAULT CHARSET=utf8;

